from crypt_lib import *

gen = Generator()
gen.generate_book("book", 100)
enc = Encryptor()
dec = Decryptor()
a = enc.encrypt_bytes('abc'.encode('utf8'))
print(a)
print(dec.decrypt_bytes(a).decode('utf8'))
a = enc.encrypt_bytes('def'.encode('utf8'))
print(a)
print(dec.decrypt_bytes(a).decode('utf8'))
enc.erase_end()
dec.erase_end()
a = enc.encrypt_bytes('hello world'.encode('utf8'))
print(a)
print(dec.decrypt_bytes(a).decode('utf8'))
a = enc.encrypt_bytes('LOL!'.encode('utf8'))
print(a)
print(dec.decrypt_bytes(a).decode('utf8'))
print("_____________")
print(enc.length)
